version: "3.3"

services:
  # MySQL
  mysql:
    # path配下のDockerfile読み込み
    build: ./mysql
    # コンテナが落ちたら再起動する
    restart: always
    tty: true
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password # ユーザのパスワード
      MYSQL_ROOT_PASSWORD: password # ルートパスワード
      TZ: Asia/Tokyo
    expose:
      - "3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d # 定義どおりにテーブル作成
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQLの基本設定(文字化け対策)
      - ./mysql/logs:/var/log/mysql # ログの保存
    networks:
      - backend

  # FastAPI
  fasrapi:
    # path配下のDockerfile読み込み
    build: ./api
    tty: true
    stdin_open: true
    ports:
      - "8080:8080"
    volumes:
      - ./api/src:/usr/src/server
    networks:
      - backend

# コンテナ間で通信を行うためのネットワークブリッジ
networks:
  backend:
    driver: bridge
